### PR TITLE
Fix spelling mistakes, use a Python library for ngrok

### PR DESCRIPTION
**Pull request by leeceeksdee**
Looks like we made changes at the same time, which means some conflicts will have to be resolved :P

More details:
- `tmux` is no longer installed because it is unused
- `openjdk-11-jre` is used instead of `openjdk-11-jdk`. It's the same thing without tools that are used to compile Java apps
- `pyngrok` is used to connect to ngrok
- everything is started in a single cell

I also wrote a script that automatically accepts the EULA (which is somewhat hard to do in Google Drive without 3rd-party apps)

### CODE REVIEW

**Review by thecoder-001 — APPROVED** [review]

**Comment by leeceeksdee** [comment]
I believe you have to resolve the conflicts by reverting https://github.com/thecoder-001/MineColab/commit/2a53fcf103e9601b3d120774e4ab78e9668e32db.

**Comment by thecoder-001** [comment]
Thanks a lot for the commit

**Comment by thecoder-001** [comment]
I guess I must add the https://www.minecraft.net/en-us/eula into the EULA section to prevent any legal problems.
Also, for future reference, you can actually edit files stored on your drive from the notebook.
Screen Shot 2020-09-27 at 7 05 41 PM
Screen Shot 2020-09-27 at 7 06 42 PM

**Comment by leeceeksdee** [comment]
I didn't see that option. Thanks!

> Thanks a lot for the commit

No problem. I really love this project; keep this up!

**Pull request merged**
