### PR TITLE
Add Cloudflare Argo for hosting

### PR DESCRIPTION
**Pull request by AndreVuillemot160**
The PR resolves https://github.com/thecoder-001/MineColab/issues/24
For game hosting it will use Cloudflare Argo tunnel instead of ngrok
The debugging part is still on ngrok

### CODE REVIEW

**Comment by AndreVuillemot160** [comment]
The Argo tunnel doesn't require ffrom users making an account like in ngrok. Thee only thing that's needed is to get cloudflared client

**Comment by thecoder-001** [comment]
Looks to be pretty good. But in my opinion retaining ngrok as an option would be pretty nice as sometimes installing the client isn't possible for those connecting to the server. Maybe readd it behind an if statement?

**Comment by AndreVuillemot160** [comment]
Hm. If you want to keep ngrok then sure. I will add a cell with original one.

**Comment by AndreVuillemot160** [comment]
Basically, Argo will serve us an backup right?

**Comment by thecoder-001** [comment]
> Basically, Argo will serve us an backup right?

Yup. Or if you wish to, you can keep ngrok as backup and make Argo default.

**Comment by thecoder-001** [comment]
Merging the commit. Would readd ngrok manually after that to main branch. Thanks a lot for contributing!

**Pull request merged**
